### ISSUE TITLE
是否能提供thunderbird的预编译包

### ISSUE THREAD

**Issue by haowuge** [lshw/loongson#4]
目前debian-ports没有雷鸟，是否能帮忙打包一个，谢谢
http://mirrors.ustc.edu.cn/bjlx/pool/main/

**Comment by lshw** [comment]
雷鸟的deb源码里， 带了很多的python的组件， 这些组件， 有些依赖， 跟debian13带的python的组件的版本有冲突， 需要一个一个调整， 还是等debian的官方团队， 去完成吧。

**Comment by haowuge** [comment]
> 雷鸟的deb源码里， 带了很多的python的组件， 这些组件， 有些依赖， 跟debian13带的python的组件的版本有冲突， 需要一个一个调整， 还是等debian的官方团队， 去完成吧。

好的，谢谢
